### PR TITLE
fix: allow only except handler with a type in try-star blocks

### LINKED ISSUE #17: pysource-codegen genereates try-blocks without except handlers
The reason is that it actually generates TryStar nodes and removes every except handler which has a no type (because a TryStar handler needs a type).

A TryStar ends up with out any exception handler if it every handler has type no type.

pseudo code:
``` python
try:
    pass
except*: # removed
    pass
except*: # removed
    pass
```

The TryStar look then like a Try because it has no `except*` blocks anymore.

the issue was discovered here:

https://github.com/15r10nk/pysource-minimize/issues/12

### PR DESCRIPTION
**Pull request by 15r10nk**
fix #17

### CODE REVIEW

**Comment by pawamoy** [comment]
It seems like I still get `try: pass` without except or finally with this branch.

**Comment by 15r10nk** [comment]
I will look into it.

**Comment by 15r10nk** [comment]
hi @pawamoy, I fixed a bit more and plan to do a release in maybe 8h with the current branch.

I tested this branch 1 day with multiple seeds and did not found another issue where pysource-codegen generates invalid code. I think I have to dig deeper if you still find issues with this version.
This would mean that I have a flaw in my tests or you are extremely lucky. I would need your seed to reproduce the bug in this case. It is no problem if you are not able to test this branch before I release. I would just make another release for the next issue.

Thank you again for the bug report.

**Comment by pawamoy** [comment]
Installed from commit fa8fb6cc27d6e8f24837b995702ea85df1fc95ec, still getting the error. A few seeds failing: 476872, 84642, 236591, 899834, 637836, 247085, 620248, 192185, 160515, 359966, 260415, 508273. Even 4, 5, 7 and 8 fail.

**Comment by 15r10nk** [comment]
I tested your seed with the following script:

``` python
from pysource_codegen import generate
import sys

print(sys.version)

seed=476872
code=generate(seed)
compile(code,"<code>","exec")
```

and got

```
3.11.0 (main, Dec 18 2022, 22:49:02) [GCC 10.2.1 20210110]
<code>:5: SyntaxWarning: 'bytes' object is not callable; perhaps you missed a comma?
<code>:87: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
```
I'm not able to reproduce your issue.

can it be that you changed the version but did not updated the installed package for some reason?

**Comment by 15r10nk** [comment]
I don't think that there is anything wrong with the fuzz task. Another idea might be that this are revisited seeds/files?

**Comment by pawamoy** [comment]
OK this is curious. I'll try to simplify my task to see if it changes anything.

**Comment by pawamoy** [comment]
I think my env was broken or something. pip was showing me the right version (installed from this branch), but it looks like running the task was using the latest version from pypi instead. I cleared everything, installed from this branch in every venv, and it works now. Apologies for the confusion and wasting your time :bow: Your fix seems to work perfectly!

**Comment by 15r10nk** [comment]
@pawamoy 0.5.1 is out. have fun

**Pull request merged**
